apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitops-operator
  source: gitops-service-source
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v0.0.4
